INSERT INTO
  artists (artist_id, artist_name)
VALUES
   (1, 'Nicholas'),
   (2, 'Jones'),
   (3, 'Melinda Wolfe'),
   (4, 'Ward, Butler and Mueller'),
   (5, 'Williams-Velasquez'),
   (6, 'Clarke-Cox'),
   (7, 'Alexander'),
   (8, 'Michael Goodman'),
   (9, 'Cabrera'),
   (10, 'Melissa Clark'),
   (11, 'Anna Hamilton'),
   (12, 'Scott PLC'),
   (13, 'Lopez-Howard'),
   (14, 'Turner, Munoz and Johnson'),
   (15, 'Brandon'),
   (16, 'Horne'),
   (17, 'Carroll'),
   (18, 'Amanda Rogers'),
   (19, 'Dawn'),
   (20, 'Rogers-Parks'),
   (21, 'Rachel'),
   (22, 'Roth'),
   (23, 'Johnson'),
   (24, 'Santos'),
   (25, 'Christopher'),
   (26, 'Daniel'),
   (27, 'Mike'),
   (28, 'Corey Mueller'),
   (29, 'Key-Wright'),
   (30, 'Matthew'),
   (31, 'Jonathan Davis'),
   (32, 'Cody'),
   (33, 'Sandra'),
   (34, 'Andrea'),
   (35, 'Hernandez-Schmidt'),
   (36, 'Lee'),
   (37, 'Matthew Wade'),
   (38, 'Lindsey'),
   (39, 'Desiree Cohen'),
   (40, 'Jennifer Ingram'),
   (41, 'Zachary Morris'),
   (42, 'Wright'),
   (43, 'Jeffery Hunt'),
   (44, 'David Mendoza'),
   (45, 'Samuel Quinn'),
   (46, 'Austin'),
   (47, 'Powell, Owen and Rocha'),
   (48, 'Frank'),
   (49, 'Brown'),
   (50, 'Don');
